<?php

use App\creational\Pool\Car;
use App\creational\Pool\CarPool;
use Tests\TestCase;

class PoolTest extends TestCase
{

    /**
     * A basic feature test example.
     *
     * @return void
     */
    /**  @test */

private $carpool;
protected function setUp(): void
{
    parent::setUp(); // TODO: Change the autogenerated stub
$this->carpool=new CarPool();

}
    /**
     * A basic feature test example.
     *
     * @return void
     */
    /**  @test */
public function TestCanRentCar()
{
    $myCar=$this->carpool->rentCar();
    $myCar2=$this->carpool->rentCar();
    $this->carpool->freeCar($myCar);
    $this->assertInstanceOf(Car::class,$myCar);
    $this->assertEquals('2',$this->carpool->getReport());
    $this->assertEquals('1',$this->carpool->getfreecount());
    $this->assertEquals('1',$this->carpool->getbusycount());
}
}
